### ISSUE TITLE
オススメされたOffer, いいねしたOffer をそれぞれ返却するAPIが欲しい

### ISSUE THREAD

**Issue by tkc-alien** [tooooofu24/DMND#1]
ユーザごとにおすすめされたオファー、いいねしたオファーを表示する要件があるので、それらのAPIが欲しいです。
オススメのアルゴリズムが未定だと思うので、とりあえず適当に5~6個くらい返すように形だけ作ってもらえれば大丈夫です。

**Comment by tooooofu24** [comment]
対応しました。
仕様書通りです。
https://app.swaggerhub.com/apis-docs/tooooofu24/DMND/1.0.0

**Comment by tkc-alien** [comment]
確認しました。
