### ISSUE TITLE
Offersの検索条件に "buyer_id", "seller_id" を追加する

### ISSUE THREAD

**Issue by tkc-alien** [tooooofu24/DMND#10]
User情報に buyer_offers, seller_offers を含めない構成に変更したため、それに該当する情報を取得する手段として表題の通りの機能を追加してほしいです。優先度は高くありません。

**Comment by tooooofu24** [comment]
Swaggerに記載済み
未実装

**Comment by tooooofu24** [comment]
@tkc-alien 
実装まで終わりました。
