### ISSUE TITLE
statusに評価後の値を追加

### ISSUE THREAD

**Issue by tooooofu24** [tooooofu24/DMND#16]

**Comment by tooooofu24** [comment]
statusに`600: 買い手が評価した`を追加しました。
ダミーデータにも反映しています。

**Comment by tkc-alien** [comment]
「買い手が評価した」は「買い手が受け取り通知を出した」と同じタイミングなので、600番は「売り手が評価した」になると思います。

**Comment by tooooofu24** [comment]
@tkc-alien 
間違えました。直しました。
