### ISSUE TITLE
Usersのレスポンスに平均評価値を含める

### ISSUE THREAD

**Issue by tkc-alien** [tooooofu24/DMND#17]

**Comment by tkc-alien** [comment]
評価された件数も追加でお願いします。

**Comment by tooooofu24** [comment]
`evaluation_score `,`evaluated_count `というプロパティを追加しました。
https://app.swaggerhub.com/apis-docs/tooooofu24/DMND/1.0.0#/User

**Comment by tooooofu24** [comment]
@tkc-alien 
対応しました。
