### ISSUE TITLE
offersに対するGETで、詳細条件を指定したい

### ISSUE THREAD

**Issue by tkc-alien** [tooooofu24/DMND#2]
オファー検索機能実装のため、offers GETで詳細条件を指定できるようにして欲しいです。
具体的には
・クエリ（文字列のリスト）（AND検索）
・小カテゴリID（整数のリスト）（OR検索）
・未成立限定フラグ（0 or 1）
・商品状態（整数）
が最低限必要だと思います。
要件の変更がある可能性が高いので、その際は別途対応をお願いします。

**Comment by tooooofu24** [comment]
対応しました。ご確認お願いします

**Comment by tkc-alien** [comment]
確認しました。
