### ISSUE TITLE
オファーの取引完了日時を取得したい

### ISSUE THREAD

**Issue by tkc-alien** [tooooofu24/DMND#3]
Offerオブジェクトについて、その取引が完了した（買い手・売り手の双方が完了を通知した）日時を任意のタイミングで取得する要件があるので、Offerのパラメータとして管理するようにしてほしいです。

今のところ、取引が完全に完了した日時のみですが、今後はそれ以外のステータス変化（DEALされた、買い手がDEALを承諾した、買い手が支払いを完了した、売り手が発送通知を出した、買い手が受取通知を出した）に応じて日時を保存する必要が出てくる可能性が高いため、管理方法についても多少検討の余地がありそうです。

**Comment by tkc-alien** [comment]
早速ですが要件が変更になり、上述のデータはすべて持っておく必要がありそうなので、こちらも併せて対応お願いします。

**Comment by tooooofu24** [comment]
Duplicate of #7
