### ISSUE TITLE
User情報取得時のbuyer_offers, seller_offersに完全なオファー情報を含めてほしい

### ISSUE THREAD

**Issue by tkc-alien** [tooooofu24/DMND#4]
User情報を単体でGETした時にレスポンスに含まれる buyer_offers, seller_offers について、Offerの構造から buyer, seller, favorite_count が省略されていますが、これらを省略せずに完全な情報で取得できるようにしてほしいです。

**Comment by tooooofu24** [comment]
仕様変更のため削除
